name: "Checkout with Git LFS"

description: "Also build Git LFS environment at checkout"

inputs:
  token:
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        submodules: recursive
        lfs: true

    # https://github.com/actions/checkout/issues/270
    - run: |
        git lfs install
        git lfs pull
        git submodule foreach git lfs install
        git submodule foreach --recursive git lfs pull
      if: ${{ runner.os != 'Windows' }}
      shell: bash

    - run: |
        git lfs install
        git lfs pull
        git submodule foreach git lfs install
        git submodule foreach --recursive git lfs pull
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh

branding:
  icon: "box"
  color: "orange"