name: "Checkout with Git LFS"

description: "Also build Git LFS environment at checkout"

inputs:
  token:
    required: true
    default: ${{ github.token }}
  sparse-checkout:
    description: >
      Do a sparse checkout on given patterns.
      Each pattern should be separated with new lines
    required: false
    default: null
  sparse-checkout-cone-mode:
    description: >
      Specifies whether to use cone-mode when doing a sparse checkout.
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        submodules: recursive
        lfs: true
      if: ${{ inputs.sparse-checkout == null }}

    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        submodules: recursive
        lfs: true
        sparse-checkout: ${{ inputs.sparse-checkout }}
        sparse-checkout-cone-mode: ${{ inputs.sparse-checkout-cone-mode }}
      if: ${{ inputs.sparse-checkout != null }}

    # https://github.com/actions/checkout/issues/270
    - run: |
        git lfs install
        git lfs pull
        git submodule foreach git lfs install
        git submodule foreach --recursive git lfs pull
      if: ${{ runner.os != 'Windows' }}
      shell: bash

    - run: |
        git lfs install
        git lfs pull
        git submodule foreach git lfs install
        git submodule foreach --recursive git lfs pull
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh

branding:
  icon: "box"
  color: "orange"